import { useEffect, useMemo, useRef, useState } from "react";

// Vite supports JSON imports natively. The lockfile is generated by
// `make compile`; the run trace by `make run-gemma` (or `make run-mock`).
import lockData from "../../demo-app/agent_lock.json";
import traceData from "../../demo-app/.acg/run_trace.json";
import type { AgentLock, RunTrace } from "./types";
import { computeReplayState, totalReplayDuration } from "./lib/replay";
import { TaskGraph } from "./components/TaskGraph";
import { Sidebar } from "./components/Sidebar";
import { Toolbar } from "./components/Toolbar";
import { OrchestratorPanel } from "./components/OrchestratorPanel";
import { ResultsPanel } from "./components/ResultsPanel";

const lock = lockData as unknown as AgentLock;
const trace = traceData as unknown as RunTrace;

export default function App() {
  const totalDuration = useMemo(() => totalReplayDuration(trace), []);

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [tSeconds, setTSeconds] = useState(0);
  const [isPlaying, setPlaying] = useState(false);
  const [speed, setSpeed] = useState(1);
  const [view, setView] = useState<"replay" | "results">("replay");

  // RAF-driven replay clock. We hold the latest speed in a ref so the loop
  // doesn't restart every time the user clicks a different speed button.
  const speedRef = useRef(speed);
  useEffect(() => {
    speedRef.current = speed;
  }, [speed]);

  useEffect(() => {
    if (!isPlaying) return;
    let raf = 0;
    let last = performance.now();
    const tick = (now: number) => {
      const dtMs = now - last;
      last = now;
      setTSeconds((prev) => {
        const next = prev + (dtMs / 1000) * speedRef.current;
        if (next >= totalDuration) {
          setPlaying(false);
          return totalDuration;
        }
        return next;
      });
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [isPlaying, totalDuration]);

  const replay = useMemo(
    () => computeReplayState(trace, tSeconds),
    [tSeconds],
  );

  const handlePlay = () => {
    // If we ended, rewind first; otherwise resume from current position.
    if (tSeconds >= totalDuration) setTSeconds(0);
    setPlaying(true);
  };
  const handlePause = () => setPlaying(false);
  const handleReset = () => {
    setPlaying(false);
    setTSeconds(0);
  };

  const phaseLabel = (() => {
    switch (replay.phase) {
      case "idle":
        return "ready";
      case "orchestrator":
        return `orchestrator · ${trace.orchestrator.model || "gemma"}`;
      case "groups":
        return replay.runningGroupId
          ? `group ${replay.runningGroupId}`
          : "between groups";
      case "done":
        return `complete · ${trace.total_wall_s.toFixed(1)}s · ${trace.workers.reduce((s, w) => s + w.allowed_count, 0)} allowed / ${trace.workers.reduce((s, w) => s + w.blocked_count, 0)} blocked`;
    }
  })();

  const progressPct = totalDuration > 0 ? (tSeconds / totalDuration) * 100 : 0;

  const selectedWorker = selectedId
    ? trace.workers.find((w) => w.task_id === selectedId)
    : undefined;
  const selectedProgress = selectedId
    ? replay.workerProgress[selectedId]
    : undefined;

  return (
    <div className="app">
      <Toolbar
        isPlaying={isPlaying}
        speed={speed}
        phaseLabel={phaseLabel}
        progressPct={progressPct}
        view={view}
        onViewChange={setView}
        onPlay={handlePlay}
        onPause={handlePause}
        onReset={handleReset}
        onSpeedChange={setSpeed}
      />
      {view === "results" ? (
        <div className="canvas-wrap" style={{ gridColumn: "1 / span 2" }}>
          <ResultsPanel />
        </div>
      ) : (
        <>
          <div className="canvas-wrap">
            <TaskGraph
              lock={lock}
              selectedTaskId={selectedId}
              runningGroup={replay.runningGroupId}
              completedGroups={replay.completedGroupIds}
              workerProgress={replay.workerProgress}
              onSelect={setSelectedId}
            />
            <OrchestratorPanel orchestrator={trace.orchestrator} replay={replay} />
          </div>
          <Sidebar
            lock={lock}
            selectedTaskId={selectedId}
            worker={selectedWorker}
            workerProgress={selectedProgress}
          />
        </>
      )}
    </div>
  );
}
