import { useEffect, useMemo, useState } from "react";

// Vite supports JSON imports natively. The lockfile is generated by
// `make compile` (or `acg compile`) and lives in demo-app/.
import lockData from "../../demo-app/agent_lock.json";
import type { AgentLock } from "./types";
import { TaskGraph } from "./components/TaskGraph";
import { Sidebar } from "./components/Sidebar";
import { Toolbar } from "./components/Toolbar";

const lock = lockData as unknown as AgentLock;

const STEP_MS = 1500;

export default function App() {
  const groupList = useMemo(
    () => [...lock.execution_plan.groups].sort((a, b) => a.id - b.id),
    [],
  );

  const [selectedId, setSelectedId] = useState<string | null>(null);
  // step semantics:
  //   -1            : idle (nothing has run yet)
  //   0..N-1        : group at this index is currently "running"
  //   N             : all groups completed
  const [step, setStep] = useState(-1);
  const [isPlaying, setPlaying] = useState(false);

  useEffect(() => {
    if (!isPlaying) return;
    const handle = window.setInterval(() => {
      setStep((prev) => {
        const next = prev + 1;
        if (next >= groupList.length) {
          setPlaying(false);
          return groupList.length;
        }
        return next;
      });
    }, STEP_MS);
    return () => window.clearInterval(handle);
  }, [isPlaying, groupList.length]);

  const runningGroupId =
    step >= 0 && step < groupList.length ? groupList[step].id : null;
  const completedGroupIds = useMemo(
    () => new Set(groupList.slice(0, Math.max(0, step)).map((g) => g.id)),
    [groupList, step],
  );

  const handlePlay = () => {
    if (step < 0 || step >= groupList.length) setStep(0);
    setPlaying(true);
  };
  const handlePause = () => setPlaying(false);
  const handleReset = () => {
    setPlaying(false);
    setStep(-1);
  };

  return (
    <div className="app">
      <Toolbar
        isPlaying={isPlaying}
        onPlay={handlePlay}
        onPause={handlePause}
        onReset={handleReset}
      />
      <TaskGraph
        lock={lock}
        selectedTaskId={selectedId}
        runningGroup={runningGroupId}
        completedGroups={completedGroupIds}
        onSelect={setSelectedId}
      />
      <Sidebar lock={lock} selectedTaskId={selectedId} />
    </div>
  );
}
